import Customers from "./resources/Customer";
import Transaction from "./resources/Transactions";
import Transfer from "./resources/Transfer";
import TransferRecipient from "./resources/TransferRecipients";
import VirtualAccount from "./resources/DedicatedVirtualAccount";
import ApplePay from "./resources/ApplePay";
import Page from "./resources/Page";
import PaymentRequest from "./resources/PaymentRequest";
import Plans from "./resources/Plans";
import Products from "./resources/Products";
import Settlements from "./resources/Settlements";
import Subaccounts from "./resources/Subaccounts";
import Subscription from "./resources/Subscription";
import BulkCharges from "./resources/BulkCharges";
import Charges from "./resources/Charge";
import Disputes from "./resources/Disputes";
import Refunds from "./resources/Refunds";
import Verification from "./resources/Verification";
import Miscellaneous from "./resources/Miscellaneous";
declare const _default: {
    Customers: typeof Customers;
    Transaction: typeof Transaction;
    Transfer: typeof Transfer;
    TransferRecipient: typeof TransferRecipient;
    VirtualAccount: typeof VirtualAccount;
    ApplePay: typeof ApplePay;
    Page: typeof Page;
    PaymentRequest: typeof PaymentRequest;
    Plans: typeof Plans;
    Products: typeof Products;
    Settlements: typeof Settlements;
    Subaccounts: typeof Subaccounts;
    Subscription: typeof Subscription;
    BulkCharges: typeof BulkCharges;
    Charges: typeof Charges;
    Disputes: typeof Disputes;
    Refunds: typeof Refunds;
    Verification: typeof Verification;
    Miscellaneous: typeof Miscellaneous;
};
export default _default;
