"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Miscellaneous = exports.VerificationApi = exports.RefundsApi = exports.DisputesApi = exports.ChargesApi = exports.BulkChargesApi = exports.SubscriptionApi = exports.SubaccountsApi = exports.SettlementsApi = exports.ProductsApi = exports.PlansApi = exports.PaymentRequestApi = exports.PageApi = exports.ApplePayApi = exports.VirtualAccountApi = exports.TransferRecipientApi = exports.TransferApi = exports.TransactionApi = exports.CustomersApi = void 0;
var Customer_1 = require("./resources/Customer");
Object.defineProperty(exports, "CustomersApi", { enumerable: true, get: function () { return Customer_1.default; } });
var Transactions_1 = require("./resources/Transactions");
Object.defineProperty(exports, "TransactionApi", { enumerable: true, get: function () { return Transactions_1.default; } });
var Transfer_1 = require("./resources/Transfer");
Object.defineProperty(exports, "TransferApi", { enumerable: true, get: function () { return Transfer_1.default; } });
var TransferRecipients_1 = require("./resources/TransferRecipients");
Object.defineProperty(exports, "TransferRecipientApi", { enumerable: true, get: function () { return TransferRecipients_1.default; } });
var DedicatedVirtualAccount_1 = require("./resources/DedicatedVirtualAccount");
Object.defineProperty(exports, "VirtualAccountApi", { enumerable: true, get: function () { return DedicatedVirtualAccount_1.default; } });
var ApplePay_1 = require("./resources/ApplePay");
Object.defineProperty(exports, "ApplePayApi", { enumerable: true, get: function () { return ApplePay_1.default; } });
var Page_1 = require("./resources/Page");
Object.defineProperty(exports, "PageApi", { enumerable: true, get: function () { return Page_1.default; } });
var PaymentRequest_1 = require("./resources/PaymentRequest");
Object.defineProperty(exports, "PaymentRequestApi", { enumerable: true, get: function () { return PaymentRequest_1.default; } });
var Plans_1 = require("./resources/Plans");
Object.defineProperty(exports, "PlansApi", { enumerable: true, get: function () { return Plans_1.default; } });
var Products_1 = require("./resources/Products");
Object.defineProperty(exports, "ProductsApi", { enumerable: true, get: function () { return Products_1.default; } });
var Settlements_1 = require("./resources/Settlements");
Object.defineProperty(exports, "SettlementsApi", { enumerable: true, get: function () { return Settlements_1.default; } });
var Subaccounts_1 = require("./resources/Subaccounts");
Object.defineProperty(exports, "SubaccountsApi", { enumerable: true, get: function () { return Subaccounts_1.default; } });
var Subscription_1 = require("./resources/Subscription");
Object.defineProperty(exports, "SubscriptionApi", { enumerable: true, get: function () { return Subscription_1.default; } });
var BulkCharges_1 = require("./resources/BulkCharges");
Object.defineProperty(exports, "BulkChargesApi", { enumerable: true, get: function () { return BulkCharges_1.default; } });
var Charge_1 = require("./resources/Charge");
Object.defineProperty(exports, "ChargesApi", { enumerable: true, get: function () { return Charge_1.default; } });
var Disputes_1 = require("./resources/Disputes");
Object.defineProperty(exports, "DisputesApi", { enumerable: true, get: function () { return Disputes_1.default; } });
var Refunds_1 = require("./resources/Refunds");
Object.defineProperty(exports, "RefundsApi", { enumerable: true, get: function () { return Refunds_1.default; } });
var Verification_1 = require("./resources/Verification");
Object.defineProperty(exports, "VerificationApi", { enumerable: true, get: function () { return Verification_1.default; } });
var Miscellaneous_1 = require("./resources/Miscellaneous");
Object.defineProperty(exports, "Miscellaneous", { enumerable: true, get: function () { return Miscellaneous_1.default; } });
